# Makefile for Sphinx documentation
#

# You can set these variables from the command line.
VAR=test

# Internal variables.
DIRECTORY=../eggs

.PHONY: help bootstrap remove

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  bootstrap       to bootstrap a new project"
	@echo "  remove          to remove all files and folders generated by bootstrap"

bootstrap:
	cp templates/* ../
	mkdir -p $(DIRECTORY)
	cd .. && python bootstrap.py

remove:
	rm -rf ../bin/ ../develop-eggs/ ../eggs/ ../parts/ ../etc/ ../bootstrap.py ../buildout.cfg ../development.cfg ../production.cfg ../staging.cfg
