# Makefile for Sphinx documentation
#

# You can set these variables from the command line.
VAR=test

# Internal variables.
EGG_DIRECTORY=../eggs

.PHONY: help bootstrap remove

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  bootstrap       to bootstrap a new project"
	@echo "  remove          to remove all files and folders generated by make bootstrap"

bootstrap:
	cp -p templates/Makefile ../ 
	cp -p templates/bootstrap.py ../ 
	cp -p templates/buildout.cfg ../ 
	cp -p templates/development.cfg ../ 
	cp -p templates/staging.cfg ../ 
	cp -p templates/production.cfg ../
	mkdir -p $(EGG_DIRECTORY)
	cd .. && python bootstrap.py && bin/buildout

remove:
	rm -rf ../bin/ 
	rm -rf ../develop-eggs/ 
	rm -rf ../eggs/ 
	rm -rf ../parts/ 
	rm -rf ../etc/ 
	rm -rf ../src/*recipe*/
	rm -rf ../.installed.cfg 
	rm -rf ../.mr.developer.cfg
	rm -rf ../Guardfile
	rm -rf ../Makefile
	rm -rf ../Watchfile
